name: khilonjiya_com
description: A comprehensive marketplace application built with Flutter for khilonjiya.com

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  provider: ^6.1.1
  
  # UI & Responsive Design
  sizer: ^2.0.15
  
  # Backend & Authentication
  supabase_flutter: ^2.3.4
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.2
  
  # Environment Variables (IMPORTANT - Added for Supabase)
  flutter_dotenv: ^5.1.0
  
  # Storage & Preferences
  shared_preferences: ^2.2.2
  
  # Location Services
  geolocator: ^10.1.0
  
  # Image Handling
  image_picker: ^1.0.8
  cached_network_image: ^3.3.1
  
  # UI Components
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.4
  package_info_plus: ^8.3.0
  
  # HTTP & Networking
  http: ^1.1.2
  
  # Local Storage
  sqflite: ^2.3.2
  path: ^1.8.3
  
  # Notifications
  flutter_local_notifications: ^18.0.0
  
  # Permissions
  permission_handler: ^11.2.0
  carousel_slider: ^5.1.1
  font_awesome_flutter: ^10.7.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  flutter_google_places_hoc081098: ^1.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    # Environment configuration (IMPORTANT - Added for Supabase)
    - .env
    
    # App assets
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700